### ISSUE TITLE
Glitches with wings mod and glitches with player form shifting 

### ISSUE THREAD

**Issue by Allycat2208** [raphaelgoldstein/hiraeth_spirits#1]
Hey! So I decided to try out this mod to see what it was like in hopes I can use it once updated in the future. I was planning to add this to a 1.16.5 mod pack I’m making with friends if this mod is updated to that version. I ran into some problems when testing it with another mod though. It seems that the color selector also changes other things that are added onto the player. 
![Uploading 8C5D03AD-A8E0-4541-AC1D-63E58A36818F.jpeg…]()

I also ran into problem when the character changes form in any way.
![Uploading 7CA39E73-2D08-4F8D-9152-314EC37D744E.jpeg…]()

![Uploading A7DF8492-CE10-41BD-BBCD-E93ADBA514F4.jpeg…]()

The horns, antlers and ears seem to stay in the same place and aren’t locked onto the player. This is more so a bigger issue than the first because the first issue is only in combination with the wings mod. However I bring it up (partly because I desperately do want to combine it with the wing mod in the future) and also because in future versions of Minecraft the character also switches positions when swimming. I haven’t received any indication that you will update this mod but I really hope you do! It’s really fantastic and adds (in my opinion) much cuter designs than other mods like “more player models” so if in the future you do decide to update this to 1.16.5, these are some bugs that I noticed :)

**Comment by raphael-emerald** [comment]
Could you send me those photos again (assuming you have them)?

unfortunately i don't have much time to work on this mod like i wish i had, but i do want to try and fix this for you and future users of the mod.
@Allycat2208

**Comment by Allycat2208** [comment]
Hi! Omg I’m so excited you responded to me. I think there is an issue with the way photos are displayed on here. Is there an alternative way I can send those pictures to you? @raphaelgoldstein

**Comment by raphael-emerald** [comment]
Feel free to DM me on discord.

**Comment by raphael-emerald** [comment]
Issue fixed and closed in version 1.12.2-1.2 :)
